---
- name: Install Zabbix-agent
  hosts: all
  become: yes
  
  tasks:
  - name: Install Zabbix-agent
    apt: name=zabbix-agent state=present
    register: Status_zabbix

  - debug:
      var: Status_zabbix

  - name: Start Zabbix-agent on th every boot
    service: name=zabbix-agent state=started enabled=yes

  handlers:
  - name: Restart Zabbix
    service: name=zabbix-agent state=restarted